### ISSUE TITLE
Problem running Region-Flags

### ISSUE THREAD

**Issue by TrueDivinity** [Olink/Region-Flags#13]
When i try to run my server with region-flags i get this error:

[03/17/16 14:52:00] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "Region flags." has thrown an exception during initialization. ---> System.TypeLoadException: Could not load type 'TShockAPI.Log' from assembly 'TShockAPI, Version=4.3.12.0, Culture=neutral, PublicKeyToken=null'.
   at RegionFlags.RegionFlags.Database()
   at RegionFlags.RegionFlags.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)

Please any sort of help would be appreciated

**Comment by Olink** [comment]
Yes, since this plugin has not been updated in years, it is unlikely to work for anymore.
